Repository alma-oss/cookie-consent-manager, pull requests merged in 2021-11, with the labels that each got.

#18 Chore/release drafter
  .github/pr-labeler.yml
  .github/workflows/pr-meta.yaml
Labels: chore

#39 Chore: Use .yarnrc instead of .npmrc because we are using yarn
  .npmrc
  .yarnrc
Labels: maintenance

#38 Chore: Rename pr-labeler config file to use yaml extension everywhere
  .github/pr-labeler.yaml
  .github/workflows/pr-meta.yaml
Labels: maintenance

#35 Chore: Introduce dependabot configuration for automated deps updates
  .github/dependabot.yaml
Labels: maintenance

#30 Feat: Introduce new design connected to Spirit design tokens #CCM-7
  .browserslistrc
  README.md
  examples/index.html
  package.json
  postcss.config.js
  src/LmcCookieConsentManager.scss
  src/scss/_cc-theme.scss
  src/scss/_settings.scss
  src/scss/_style.scss
  src/scss/_theme.scss
  src/scss/_tools.scss
  src/scss/index.scss
  yarn.lock
Labels: feature

#40 Chore: Remove prepare script before publishing package
  .github/workflows/publish.yaml
  package.json
  scripts/remove-prepare.js
Labels: maintenance

#51 Chore: Fix path change in spirit-design-token@0.4.1
  package.json
Labels: bugfix

#52 Docs: Minor readme improvements
  README.md
Labels: documentation

#55 Remove themeCss config property #CCM-28
  README.md
  src/LmcCookieConsentManager.js
Labels: BC

#57 Chore: Skip breaking changes until package is stable
  bin/ci/semver.sh
Labels: maintenance

#60 Docs: Update list of supported languages
  README.md
Labels: documentation

#61 Docs: Do not use patch part in URL to update to bugfix versions automatically
  README.md
  scripts/readme-replace-version.js
Labels: documentation

#68 Require service name to be passed as the first param
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/theming.html
  src/LmcCookieConsentManager.js
Labels: feature

#70 Feat: Generate and store consent UUID on accept
  package.json
  src/LmcCookieConsentManager.js
Labels: feature

#74 Chore: Fix building when using crypto in nanoid
  scripts/build.js
Labels: maintenance

#79 Chore: Cache yarn dependencies to increase GH Actions jobs speed
  .github/workflows/commitlint.yaml
  .github/workflows/lint.yaml
  .github/workflows/test.yaml
Labels: maintenance

#81 Fix: Make `font-family` fallback actually work as documented
  src/scss/_theme.scss
Labels: bugfix

#73 Feat: Submit consent to the API
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/theming.html
  src/LmcCookieConsentManager.js
  src/consentCollector.js
Labels: feature

#78 Refactor: Extract assemble config into variable
  src/LmcCookieConsentManager.js
Labels: refactoring

#86 Docs: Add example of localStorage clear
  examples/configuration.html
Labels: documentation

#83 Feat: Autodetect language based on the value of <html lang=...>
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/theming.html
  package.json
  src/LmcCookieConsentManager.js
  yarn.lock
Labels: feature

#82 Feat: Submit to API also current language and cookie expiration #CCM-41
  package.json
  src/consentCollector.js
  yarn.lock
Labels: feature

#92 Chore: Fix condition to generate `minor` on both cases
  bin/ci/semver.sh
Labels: maintenance

#96 Chore: Add ignored internal URL to link check config
  .github/markdown-link-check-config.json
Labels: maintenance

#101 Chore: Merge linting into test workflow
  .github/workflows/lint.yaml
  .github/workflows/markdown-link-check.yaml
  .github/workflows/test.yaml
  README.md
Labels: maintenance

#111 Docs: Use switches instead of buttons to demonstrate theming
  examples/theming.html
Labels: documentation
