Repository alma-oss/cookie-consent-manager, pull requests merged in 2021-12, with the labels that each got.

#112 BREAKING CHANGES: Update buttons theming API according to the latest design
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/theming.html
  src/scss/_cc-theme.scss
  src/scss/_style.scss
  src/scss/_theme.scss
Labels: BC

#116 Fix: Add missing 'ads' level to dataLayer
  src/LmcCookieConsentManager.js
Labels: bugfix

#119 Fix: Use proper level name stored to dataLayer
  src/LmcCookieConsentManager.js
Labels: bugfix

#126 Docs: Extend examples for inline `<script>` usage
  README.md
  examples/index.html
Labels: documentation

#141 Chore(renovate): Set `separateMajorMinor` to false for devDependencies
  renovate.json
Labels: maintenance

#127 Chore: Prepare for stable release
  README.md
  bin/ci/semver.sh
  scripts/readme-replace-version.js
Labels: maintenance

#142 Chore(renovate): Schedule dependency updates on weekly basis
  renovate.json
Labels: maintenance

#147 Docs: Change text color of success state to improve its contrast with background
  examples/assets/examples.css
Labels: documentation

#148 Docs(lighthouse): Fix errors reported by Google Lighthouse in examples
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/theming.html
Labels: bugfix

#149 Chore: Label bugfix pull requests with "bug" label
  .github/pr-labeler.yaml
Labels: maintenance

#155 Chore: Do not lint build.js in examples
  .eslintignore
Labels: maintenance

#159 Chore: Annotate the CommonJS export names for ESM import in Node
  package.json
  scripts/build.js
Labels: maintenance, bug

#161 Refactor: Use category instead of level in type names
  src/LmcCookieConsentManager.ts
  src/consentCollector.ts
  src/languages/cs.ts
  src/languages/de.ts
  src/languages/en.ts
  src/languages/hu.ts
  src/languages/pl.ts
  src/languages/ru.ts
  src/languages/sk.ts
  src/languages/uk.ts
  src/types/CookieConsentCategory.ts
  src/types/CookieConsentManager.ts
  src/types/index.ts
  src/types/vanilla-cookieconsent.ts
Labels: refactoring

#150 Feat: Attempt to overlap UI of other third-party plugins
  src/scss/_style.scss
Labels: feature

#151 Feat: Add more theming options for links and buttons
  README.md
  src/scss/_style.scss
  src/scss/_theme.scss
Labels: feature

#165 Fix: Apply link text decoration also for secondary button
  src/scss/_style.scss
Labels: bug

#160 Chore: Improve jest tests performance
  config/jest.config.json
  tsconfig.json
Labels: maintenance

#168 Fix(types): Make options to be optional
  src/types/CookieConsentManager.ts
Labels: bug

#166 Feat: Make texts for cs, en, sk and pl less formal #CCM-50
  src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
  src/languages/cs.ts
  src/languages/en.ts
  src/languages/pl.ts
  src/languages/sk.ts
Labels: feature

#162 Deps: Update and pin to vanilla-cookieconsent 2.7.1 #CCM-51
  package.json
  yarn.lock
Labels: dependencies

#154 Refactor: Enable new swap_buttons feature to proper button order by default
  src/LmcCookieConsentManager.ts
  src/scss/_style.scss
Labels: refactoring

#174 Fix: Add missing cookie_name type in vanilla-cookieconsent declaration
  src/types/vanilla-cookieconsent.ts
Labels: bug

#167 Chore(changelog): Switch from bitbucket preset to Github preset
  CHANGELOG.md
  package.json
Labels: maintenance

#175 Fix: Fix spacing too big after core library upgrade
  src/scss/_style.scss
Labels: bug
