Repository alma-oss/cookie-consent-manager, pull requests merged in 2022-02, with the labels that each got.

#199 Chore: Watch and build SCSS during development
  package.json
  yarn.lock
Labels: maintenance

#202 Docs: Prefer `DOMContentLoaded` over `load` event to render cookie consent modal earlier
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/languages.html
  examples/theming.html
  examples/webpack-with-esm/index.js
Labels: documentation

#206 Docs: Rework callback examples #CCM-57
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/languages.html
  examples/theming.html
Labels: documentation

#207 Docs: Clearly state the plugin is mainly for LMC products
  README.md
  package.json
Labels: documentation

#209 Docs: Extend configuration example page to showcase onChange event
  examples/configuration.html
Labels: documentation

#210 Docs: List allowed categories also on callbacks example page
  examples/assets/functions.js
  examples/callbacks.html
  examples/index.html
Labels: documentation

#211 Feat: Submit consent to API and dataLayer also on settings change
  src/LmcCookieConsentManager.ts
Labels: feature

#213 Docs(upgrade): Fix typo
  UPGRADE-2.0.md
Labels: documentation
