Repository alma-oss/cookie-consent-manager, pull requests merged in 2022-04, with the labels that each got.

#233 Deps: Force dependency update of vulnerable minimist
  yarn.lock
Labels: dependencies

#235 Fix unreachable content
  src/scss/style/_consent-modal.scss
Labels: bug

#234 Feat: Add secondaryButtonMode to choose secondary button behavior
  README.md
  examples/configuration.html
  src/LmcCookieConsentManager.ts
  src/__tests__/utils.test.ts
  src/constants/SecondaryButtonMode.ts
  src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
  src/languages/__tests__/langConfig.test.ts
  src/languages/cs.ts
  src/languages/de.ts
  src/languages/en.ts
  src/languages/hu.ts
  src/languages/pl.ts
  src/languages/ru.ts
  src/languages/sk.ts
  src/languages/uk.ts
  src/types/CookieConsentManager.ts
  src/types/vanilla-cookieconsent.ts
  src/utils.ts
Labels: feature
