Repository alma-oss/cookie-consent-manager, pull requests merged in 2025-02, with the labels that each got.

#416 Docs: Update README header to clearly states affiliation of the library
  README.md
Labels: documentation

#421 Feat: Add Romanian (ro) translation
  README.md
  examples/languages.html
  src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
  src/languages/__tests__/langConfig.test.ts
  src/languages/__tests__/loader.test.ts
  src/languages/loader.ts
  src/languages/ro.ts
Labels: feature

#427 Docs: Sort languages in docs by their name, not code
  README.md
  examples/languages.html
Labels: documentation

#425 BREAKING CHANGE: Update Spirit design tokens to v3
  README.md
  UPGRADE-3.0.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/languages.html
  examples/theming.html
  examples/webpack-with-esm/index.html
  examples/webpack-with-typescript/index.html
  package.json
  src/CookieConsentManager.scss
  src/CookieConsentManagerThemes.scss
  src/scss/index.scss
  src/scss/main.scss
  src/scss/settings/_settings.scss
  src/scss/style/_buttons.scss
  src/scss/style/_consent-modal.scss
  src/scss/style/_links.scss
  src/scss/style/_main.scss
  src/scss/style/_preferences-modal.scss
  src/scss/style/_toggles.scss
  src/scss/style/_typography.scss
  src/scss/theme/_default-to-vanilla.scss
  src/scss/theme/_default.scss
  src/scss/theme/_spirit.scss
  src/scss/themes.scss
  src/scss/tools/_breakpoint.scss
  src/scss/tools/_themes.scss
  src/scss/tools/_typography.scss
  src/scss/tools/_units.scss
  yarn.lock
Labels: BC
