Repository alma-oss/cookie-consent-manager, pull requests merged in 2025-01, with the labels that each got.

#390 BREAKING CHANGE: Rename callbacks
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/languages.html
  examples/theming.html
  src/LmcCookieConsentManager.ts
  src/types/CookieConsentManager.ts
Labels: BC

#401 BREAKING CHANGE: Change library npm organization to almacareer
  README.md
  bin/ci/npm-auth.sh
  examples/webpack-with-esm/index.js
  examples/webpack-with-esm/package.json
  examples/webpack-with-typescript/index.ts
  examples/webpack-with-typescript/package.json
  package.json
Labels: BC

#404 Chore: Update version replace script to ESM
  package.json
  scripts/readme-replace-version.ts
  yarn.lock
Labels: maintenance

#402 Docs: Add UPGRADE guide for version 3
  README.md
  UPGRADE-3.0.md
Labels: documentation

#407 Chore: Update codeowners
  .github/CODEOWNERS
Labels: maintenance

#403 Feat: Use new default consentCollectorApiUrl with a new resource type
  README.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/languages.html
  examples/theming.html
  src/CookieConsentManager.ts
Labels: feature

#408 Docs: Add catalog info for Backstage
  catalog-info.yaml
Labels: documentation

#411 Chore: Move repository from lmc-eu to alma-oss
  .github/markdown-link-check-config.json
  CHANGELOG.md
  README.md
  UPGRADE-2.0.md
  examples/callbacks.html
  examples/configuration.html
  examples/index.html
  examples/languages.html
  examples/theming.html
  package.json
  src/CookieConsentManager.scss
Labels: maintenance

#412 Docs: Add link to consumed API into catalog-info
  catalog-info.yaml
Labels: documentation
